sudo: required
services:
    - docker
script:
    - docker build -t solmn/node .
    - docker images solmn/node
deploy:
    provider: script
    script: docker push solmn/node
    on:
        branch: master